server:
  port: 8090
spring:
  datasource:
    #mysql5必须使用安全连接useSSL=true
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yr